# Generated by Django 5.0.1 on 2024-01-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=200)),
                ('reader_name', models.CharField(max_length=200)),
                ('redear_contact', models.CharField(max_length=200)),
                ('redear_address', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
