# Generated by Django 5.0.1 on 2024-01-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_rename_redear_address_reader_readear_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='readear_address',
            new_name='reader_address',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='readear_contact',
            new_name='reader_contact',
        ),
    ]
