# Generated by Django 5.0.1 on 2024-01-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_rename_readear_address_reader_reader_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('book_isbn', models.CharField(max_length=200)),
                ('book_description', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
