# Generated by Django 5.0.1 on 2024-01-28 18:38

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0005_reader_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='reading',
        ),
        migrations.AddField(
            model_name='reader',
            name='guardian_name',
            field=models.CharField(default='Not applicable', help_text='parent/guardian full name', max_length=100),
        ),
        migrations.AddField(
            model_name='reader',
            name='reader_email',
            field=models.EmailField(default='No email address', help_text='Guardian/parent e-mail', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(blank=True, help_text='Summary about the book', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reference_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Book unique id across the Library', primary_key=True, serialize=False)),
                ('book_number', models.PositiveIntegerField(help_text='Book number for books of the save kind', null=True)),
                ('Is_borrowed', models.BooleanField(default=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lims_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now=True, help_text='Date the book is issued')),
                ('due_date', models.DateTimeField(default=datetime.datetime(2024, 2, 5, 11, 38, 0, 187474), help_text='Date the book is due to')),
                ('date_returned', models.DateField(blank=True, help_text='Date the book is returned', null=True)),
                ('remarks_on_issue', models.CharField(default='Book in good condition', help_text='Book remarks/condition during issue', max_length=100)),
                ('remarks_on_return', models.CharField(default='Book in good condition', help_text='Book remarks/condition during return', max_length=100)),
                ('reader_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.reader')),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims_app.bookinstance')),
            ],
        ),
    ]
