# Generated by Django 5.0.1 on 2024-01-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0009_remove_bookinstance_book_alter_book_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(max_length=200),
        ),
    ]
