# Generated by Django 5.0.1 on 2024-01-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0012_book_readers_alter_book_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='readers',
        ),
        migrations.AddField(
            model_name='reader',
            name='reading',
            field=models.ManyToManyField(blank=True, to='lims_app.book'),
        ),
    ]
