# Generated by Django 5.0.1 on 2024-01-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0013_remove_book_readers_reader_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='issuedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('reader_name', models.CharField(max_length=100)),
                ('reader_contact', models.CharField(max_length=200)),
                ('reader_email', models.EmailField(help_text='Guardian/parent e-mail', max_length=100)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('overdue_fee', models.IntegerField()),
                ('book_details', models.CharField(max_length=200)),
            ],
        ),
    ]
