# Generated by Django 5.0.1 on 2024-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0015_rename_reader_contact_issuedbooks_reader_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='category',
            field=models.CharField(default='reader', max_length=100),
        ),
    ]
