# Generated by Django 5.0.1 on 2024-04-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0016_reader_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='category',
            field=models.CharField(help_text='Enter: Staff or Reader only', max_length=100),
        ),
    ]
